### ISSUE TITLE
compile error with Visual Studio 15 2017 Win64 on win10

### ISSUE THREAD

**Issue by louiskoo520** [smistad/FAST#103]
UNHANDLED EXCEPTIONS FROM PROCESS 28064:
=====================
2018/5/21 14:00:57
System.OutOfMemoryException: 引发类型为“System.OutOfMemoryException”的异常。
   在 Go1(RegexRunner )
   在 System.Text.RegularExpressions.CompiledRegexRunner.Go()
   在 System.Text.RegularExpressions.RegexRunner.Scan(Regex regex, String text, Int32 textbeg, Int32 textend, Int32 textstart, Int32 prevlen, Boolean quick, TimeSpan timeout)
   在 System.Text.RegularExpressions.Regex.Run(Boolean quick, Int32 prevlen, String input, Int32 beginning, Int32 length, Int32 startat)
   在 System.Text.RegularExpressions.Regex.Match(String input, Int32 startat)
   在 System.Text.RegularExpressions.RegexReplacement.Replace(MatchEvaluator evaluator, Regex regex, String input, Int32 count, Int32 startat)
   在 System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator, Int32 count, Int32 startat)
   在 System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator)
   在 Microsoft.Build.Evaluation.Expander`2.MetadataExpander.ExpandMetadataLeaveEscaped(String expression, IMetadataTable metadata, ExpanderOptions options)
   在 Microsoft.Build.Evaluation.Expander`2.ExpandIntoStringLeaveEscaped(String expression, ExpanderOptions options, IElementLocation elementLocation)
   在 Microsoft.Build.Evaluation.Expander`2.ExpandIntoStringAndUnescape(String expression, ExpanderOptions options, IElementLocation elementLocation)
   在 Microsoft.Build.Evaluation.ConditionEvaluator.ConditionEvaluationState`2.ExpandIntoStringBreakEarly(String expression)
   在 Microsoft.Build.Evaluation.StringExpressionNode.EvaluatesToEmpty(IConditionEvaluationState state)
   在 Microsoft.Build.Evaluation.MultipleComparisonNode.BoolEvaluate(IConditionEvaluationState state)
   在 Microsoft.Build.Evaluation.GenericExpressionNode.Evaluate(IConditionEvaluationState state)
   在 Microsoft.Build.Evaluation.ConditionEvaluator.EvaluateConditionCollectingConditionedProperties[P,I](String condition, ParserOptions options, Expander`2 expander, ExpanderOptions expanderOptions, Dictionary`2 conditionedPropertiesTable, String evaluationDirectory, ElementLocation elementLocation, ILoggingService loggingServices, BuildEventContext buildEventContext, ProjectRootElementCache projectRootElementCache)
   在 Microsoft.Build.Evaluation.ConditionEvaluator.EvaluateCondition[P,I](String condition, ParserOptions options, Expander`2 expander, ExpanderOptions expanderOptions, String evaluationDirectory, ElementLocation elementLocation, ILoggingService loggingServices, BuildEventContext buildEventContext, ProjectRootElementCache projectRootElementCache)
   在 Microsoft.Build.Evaluation.Evaluator`4.EvaluateCondition(ProjectElement element, String condition, ExpanderOptions expanderOptions, ParserOptions parserOptions)
   在 Microsoft.Build.Evaluation.Evaluator`4.EvaluateItemDefinitionElement(ProjectItemDefinitionElement itemDefinitionElement)
   在 Microsoft.Build.Evaluation.Evaluator`4.EvaluateItemDefinitionGroupElement(ProjectItemDefinitionGroupElement itemDefinitionGroupElement)
   在 Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   在 Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext, ProjectInstance projectInstanceIfAnyForDebuggerOnly, SdkResolution sdkResolution)
   在 Microsoft.Build.Execution.ProjectInstance.Initialize(ProjectRootElement xml, IDictionary`2 globalProperties, String explicitToolsVersion, String explicitSubToolsetVersion, Int32 visualStudioVersionFromSolution, BuildParameters buildParameters, ILoggingService loggingService, BuildEventContext buildEventContext, SdkResolution sdkResolution)
   在 Microsoft.Build.Execution.ProjectInstance..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, BuildParameters buildParameters, ILoggingService loggingService, BuildEventContext buildEventContext)
   在 Microsoft.Build.BackEnd.RequestBuilder.LoadProjectFromFile()
   在 Microsoft.Build.BackEnd.BuildRequestConfiguration.InitializeProject(BuildParameters buildParameters, Func`1 loadProjectFromFile)
   在 Microsoft.Build.BackEnd.RequestBuilder.LoadProjectIntoConfiguration()
   在 Microsoft.Build.BackEnd.RequestBuilder.<BuildProject>d__57.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__49.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Microsoft.Build.BackEnd.RequestBuilder.<RequestThreadProc>d__48.MoveNext()
===================
2018/5/21 14:00:57
System.OutOfMemoryException: 引发类型为“System.OutOfMemoryException”的异常。
   在 Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Boolean needToValidateProject, String schemaFile, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean debugger, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages)
   在 Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)
   在 Microsoft.Build.CommandLine.MSBuildApp.Main()
===================
UNHANDLED EXCEPTIONS FROM PROCESS 28468:
=====================
2018/5/21 13:44:15
System.IndexOutOfRangeException: 索引超出了数组界限。
   在 System.Text.StringBuilder.get_Chars(Int32 index)
   在 System.Diagnostics.AsyncStreamReader.GetLinesFromStringBuilder()
   在 System.Diagnostics.AsyncStreamReader.ReadBuffer(IAsyncResult ar)
   在 System.IO.Stream.ReadWriteTask.InvokeAsyncCallback(Object completedTask)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.IO.Stream.ReadWriteTask.System.Threading.Tasks.ITaskCompletionAction.Invoke(Task completingTask)
   在 System.Threading.Tasks.Task.FinishContinuations()
   在 System.Threading.Tasks.Task.FinishStageThree()
   在 System.Threading.Tasks.Task.FinishStageTwo()
   在 System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
   在 System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   在 System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   在 System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   在 System.Threading.ThreadPoolWorkQueue.Dispatch()
   在 System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
===================
2018/5/21 13:44:15
System.IndexOutOfRangeException: 索引超出了数组界限。
   在 System.Text.StringBuilder.get_Chars(Int32 index)
   在 System.Diagnostics.AsyncStreamReader.GetLinesFromStringBuilder()
   在 System.Diagnostics.AsyncStreamReader.ReadBuffer(IAsyncResult ar)
   在 System.IO.Stream.ReadWriteTask.InvokeAsyncCallback(Object completedTask)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.IO.Stream.ReadWriteTask.System.Threading.Tasks.ITaskCompletionAction.Invoke(Task completingTask)
   在 System.Threading.Tasks.Task.FinishContinuations()
   在 System.Threading.Tasks.Task.FinishStageThree()
   在 System.Threading.Tasks.Task.FinishStageTwo()
   在 System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
   在 System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   在 System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   在 System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   在 System.Threading.ThreadPoolWorkQueue.Dispatch()
   在 System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
===================
2018/5/21 13:44:15
System.IndexOutOfRangeException: 索引超出了数组界限。
   在 System.Text.StringBuilder.get_Chars(Int32 index)
   在 System.Diagnostics.AsyncStreamReader.GetLinesFromStringBuilder()
   在 System.Diagnostics.AsyncStreamReader.ReadBuffer(IAsyncResult ar)
   在 System.IO.Stream.ReadWriteTask.InvokeAsyncCallback(Object completedTask)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.IO.Stream.ReadWriteTask.System.Threading.Tasks.ITaskCompletionAction.Invoke(Task completingTask)
   在 System.Threading.Tasks.Task.FinishContinuations()
   在 System.Threading.Tasks.Task.FinishStageThree()
   在 System.Threading.Tasks.Task.FinishStageTwo()
   在 System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
   在 System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   在 System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   在 System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   在 System.Threading.ThreadPoolWorkQueue.Dispatch()
   在 System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
===================
2018/5/21 13:44:15
System.IndexOutOfRangeException: 索引超出了数组界限。
   在 System.Text.StringBuilder.get_Chars(Int32 index)
   在 System.Diagnostics.AsyncStreamReader.GetLinesFromStringBuilder()
   在 System.Diagnostics.AsyncStreamReader.ReadBuffer(IAsyncResult ar)
   在 System.IO.Stream.ReadWriteTask.InvokeAsyncCallback(Object completedTask)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.IO.Stream.ReadWriteTask.System.Threading.Tasks.ITaskCompletionAction.Invoke(Task completingTask)
   在 System.Threading.Tasks.Task.FinishContinuations()
   在 System.Threading.Tasks.Task.FinishStageThree()
   在 System.Threading.Tasks.Task.FinishStageTwo()
   在 System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
   在 System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   在 System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   在 System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   在 System.Threading.ThreadPoolWorkQueue.Dispatch()
   在 System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
===================

**Comment by smistad** [comment]
Note sure what this is... it does not look like any build log I am used to from MSVC. You need to provide some more information: When does this error occur, where do you see it, what are you trying to build etc...

**Comment by louiskoo520** [comment]
I tried to build generated fast project . Error occured when building dcmtk project.![image](https://user-images.githubusercontent.com/4961164/40352232-e822e9c4-5de0-11e8-9129-0f5563f44903.png)
And MSbuild.failure.txt show:
![image](https://user-images.githubusercontent.com/4961164/40352313-18a66436-5de1-11e8-9084-f19f42feb1c8.png)

**Comment by smistad** [comment]
I have no idea what is causing this error, it builds fine here with Windows 10 and Visual Studio 2017. Please let me know if you find out what the problem is.

**Comment by louiskoo520** [comment]
I encountered the same problem compling on GTX 1060 with 6G GPU memory and I have no idea how to solve it.

**Comment by louiskoo520** [comment]
I success building dcmtk with cmake instaed of VS2017 .https://discourse.itk.org/t/itk-with-dcmtk-building-error/593/11
