### ISSUE TITLE
No SOVERSION

### ISSUE THREAD

**Issue by shayandoust** [smistad/FAST#121]
Hello there,

I have realised that libFAST.so contains no SOVERSION. This can be set within CMAKE itself to be set during build time. The SOVERSION can then be incremented / bumped whenever there is a change with ABI. Could start with a SOVERSION of 0. Would it be possible if you could add this?

The SOVERSION is important within packaging and the debian ecosystem with regards to ABI backwards compat and a plethora of other things.

Thanks,
Shayan

**Comment by smistad** [comment]
Sure, that should be no problem to add to cmake. However, so far I have not been good at changing version numbers when changing the API... 
I am not sure how to treat this in terms of changing existing interface and adding new methods/functions/classes to the interface. Do you have any recommendations how to do this in a pragmatic way?

Am I understanding correctly that you are trying to make a debian package of FAST?

**Comment by shayandoust** [comment]
Yes, I am packaging FAST for debian. API and ABI are different. Sometimes ABI changes are unavoidable. This means that any programs that use that that library will not work unless they are re-compiled against the new version of the library.

Keeping ABI stable does not mean not changing function interfaces, methods or classes. New functions can be added but the original functions already in the library must remain the same. This means that any programs using the existing functions and not the new ones can still remain functional. If you modify existing functions (let's say, you change some data type in a function) to which other programs already linked to your library will no longer work and need to be modified, then you can bump up your SOVERSION. It's a reason as to why multiple versions of a library can exist on debian.

Generally, I think as long as you keep the existing functions similar and not break it with every FAST release, then your SOVERSION can stay the same. As a package maintainer, I will also be a second eye to make sure ABI stays stable but yes, it's generally a difficult concept to try explain.

**Comment by smistad** [comment]
I tested adding the following to CMake:
```cmake
set_target_properties(FAST PROPERTIES VERSION "${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}" SOVERSION 0)
```

This results in the following files and symlinks:
libFAST.so -> libFAST.so.0
libFAST.so.0 -> libFAST.so.3.0.0
libFAST.so.3.0.0

Great that you are looking into packaging FAST for debian. I think handling FAST's increasing number of dependencies might be challenging in terms of packaging.

**Comment by shayandoust** [comment]
Looks great to me.

Any challenge is welcome so let this not hinder productivity :).

Thanks again. I think we can close this.
