### ISSUE TITLE
FAST.lib is not found

### ISSUE THREAD

**Issue by huangsusan** [smistad/FAST#122]
hello:
Thanks for your code.When I build this project,I meet an error ,can not open "lib\FAST.lib".I found there is no FAST.lib
I build your project with VS2015.I have QT5.7.When I Cmake ,I set Qt5Serialport_dir and do not choice FAST_BUILD_QT5, Do I have something wrong

**Comment by smistad** [comment]
Does it work if you enable FAST_BUILD_QT5?

**Comment by huangsusan** [comment]
I found If I do not choice FAST_BUILD_QT5 in Cmake.The error is disppeared.But error C2664 “void std::_Ptr_base<_Ty>::_Reset0(_Ty (*),std::_Ref_count_base *)”: can not change “uchar ”to“unsigned char ()[]” error occured in FAST memory line 695  still exist
