### ISSUE TITLE
Can this project segment coronary artery?

### ISSUE THREAD

**Issue by huangsusan** [smistad/FAST#125]
Hello:
 I build this project successfully by your modified edition,and I tried an example of airwaySegmentation using Coronary artery CTA data.
I want to segment Coronry vessal,but the result of the segmentation is bad.The result segment many things ,such as Aorta,bones,except Coronry.I use a seed which is in Coronry section.I do not know why.Could your give me some advice to get a better segamentation?

![image](https://user-images.githubusercontent.com/20455060/68470590-4fa75c80-0257-11ea-8fa4-dffca21f5498.png)

**Comment by smistad** [comment]
The airway segmentation example is made specifically for airways, not blood vessels.
You could try and and test the seeded region growing example, or the tubular segmentation algorithms.
If you have more questions please use the gitter chat channel https://gitter.im/smistad/FAST instead. The issue system for reporting bugs

**Comment by huangsusan** [comment]
OK，I see.Thank you



发自我的iPhone


------------------ Original ------------------
