### ISSUE TITLE
OpenVINO encrypted models

### ISSUE THREAD

**Issue by rolarsen** [smistad/FAST#128]
could this part "2. Read IR Generated by ModelOptimizer (.xml and .bin files)" be put into a new virtual function just for loading model and weights from memory buffers?

virtual void readNetwork(CNNNetReader network_reader);

default implementation could be something like 
void OpenVINOEngine::readNetwork(CNNNetReader network_reader) {
    auto input_model = getFilename();
    if(!fileExists(input_model))
        throw FileNotFoundException(input_model);
    network_reader.ReadNetwork(fileNameToString(input_model));
    network_reader.ReadWeights(fileNameToString(input_model).substr(0, input_model.size() - 4) + ".bin");
}

https://docs.openvinotoolkit.org/latest/_docs_IE_DG_protecting_model_guide.html

**Comment by smistad** [comment]
My suggestion is that we add an additional method called load which can load from binary buffers, so that we have the following methods:
```C++
void load(std::string filename); // Load network model directly from file
void load(std::vector<uint8_t> model, std::vector<uint8_t> weights); // Load network model from memory
```

OpenVINO can then implement this method properly, while other inference engines which may not support this can throw an exception instead.

**Comment by rolarsen** [comment]
good solution:)

**Comment by smistad** [comment]
@rolarsen do you have a setup to test the commit https://github.com/smistad/FAST/commit/9d03eb212c4e39685d019ad64dc5f44e83f06209 to see if that solution works?

**Comment by rolarsen** [comment]
@smistad - seems to work perfectly:)
