### ISSUE TITLE
Missing network assignment when loading models from memory

### ISSUE THREAD

**Issue by rolarsen** [smistad/FAST#130]
**Describe the bug**
FAST client application terminates without no message

https://github.com/smistad/FAST/blob/9d26761aba2ffae21208b9e38d3faa57edf96634/source/FAST/Algorithms/NeuralNetwork/InferenceEngines/OpenVINOEngine.cpp#L61

new line should be:  

network = m_inferenceCore->ReadNetwork(strModel, make_shared_blob<uint8_t>({Precision::U8, {m_weights.size()}, C}, m_weights.data()));

**Comment by smistad** [comment]
Fixed and pushed to master. Thanks
