### ISSUE TITLE
Can it support opencv?

### ISSUE THREAD

**Issue by libaineu2004** [smistad/FAST#145]
**Is your feature request related to a problem? Please describe.**
Can this framework be used with opencv? Can you give an official example?

**Describe the solution you'd like**

**Do you have an idea of how it can/should be implemented?**

**Are you willing to contribute to the implementation of this feature**

**Comment by smistad** [comment]
Yes. In Python, this is very simple. I added a couple of examples in the documentation: https://fast.eriksmistad.no/python-tutorial-intro.html#autotoc_md98
(you may need to refresh the page).

**Comment by libaineu2004** [comment]
> Yes. In Python, this is very simple. I added a couple of examples in the documentation: https://fast.eriksmistad.no/python-tutorial-intro.html#autotoc_md98
> (you may need to refresh the page).

OK, thanks! After opencv is integrated into this framework, will the performance be greatly improved? Can you give a chart of the performance test?

**Comment by smistad** [comment]
Depends on the algorihms used and many other factors
