### ISSUE TITLE
There are no files in the Data folder

### ISSUE THREAD

**Issue by libaineu2004** [smistad/FAST#146]
**Describe the bug**
I downloaded the file fast_windows_4.0.0.exe And install. But it is found that the content in C:\ProgramData\FAST\data is empty and there is no file.
No CT, no US, no *.uff, *.hd5, *.hdf5 these folders or files.

**To Reproduce**

**System:**
- OS and version: [e.g. Windows 10/x64]
- GPU and OpenCL vendor (NVIDIA)

**Expected behavior**

**Screenshots**

**Comment by smistad** [comment]
You need to run the download test data executable https://fast.eriksmistad.no/cpp-tutorial-intro.html#autotoc_md6

**Comment by libaineu2004** [comment]
The download speed of the command line is too slow. Can I package and upload the resources to https://github.com/smistad/FAST/releases
