### ISSUE TITLE
GVF example error

### ISSUE THREAD

**Issue by libaineu2004** [smistad/FAST#148]
**Describe the bug**

My code is :

#include "FAST/Importers/ImageFileImporter.hpp"
#include "FAST/Visualization/ImageRenderer/ImageRenderer.hpp"
#include "FAST/Visualization/SegmentationRenderer/SegmentationRenderer.hpp"
#include "FAST/Visualization/SimpleWindow.hpp"
#include "FAST/Algorithms/GradientVectorFlow/EulerGradientVectorFlow.hpp"
#include "FAST/Algorithms/GradientVectorFlow/MultigridGradientVectorFlow.hpp"

using namespace fast;

int main() {
    auto importer = ImageFileImporter::create("d:\\1.jpg");
    auto gvf = MultigridGradientVectorFlow::create()->connect(importer);
	auto imageRenderer = ImageRenderer::create()->connect(importer);
	auto segmentationRenderer = SegmentationRenderer::create()->connect(gvf);
	auto window = SimpleWindow2D::create()->connect({ imageRenderer, segmentationRenderer });
#ifdef FAST_CONTINUOUS_INTEGRATION
	// This will automatically close the window after 5 seconds, used for CI testing
	window->setTimeout(5 * 1000);
#endif
	window->run();
    return 0;
}

The source code can be compiled, but it will run into errors!

**To Reproduce**
The source code can be compiled, but it will run into errors.Run will throw an exception.

virtual bool notify(QObject *receiver, QEvent *event) {
        try {
            return QApplication::notify(receiver, event);
        } catch(Exception &e) {
            Reporter::error() << "FAST exception caught in Qt event handler " << e.what() << Reporter::end();
            throw e;

**System:**
- OS and version: [e.g. Windows 10]
- GPU and OpenCL vendor (NVIDIA,  Intel)

**Expected behavior**
Can you give an example to correctly use EulerGradientVectorFlow and MultigridGradientVectorFlow?

**Screenshots**
![image](https://user-images.githubusercontent.com/11898277/133015595-c388e54c-42ad-4dd1-a985-d74740248fa6.png)

**Comment by smistad** [comment]
A couple of comments to your code:
* Input to gradient vector field (GVF) has to be a vector field, not an image. Thus use ImageGradient on your image first
* MultigridGradientVectorFlow only supports 3D, for 2D use EulerGradientVectorFlow
* GVF is not a segmentation algorithm, but it can be used for segmentation. Output of GVF is a vector field, so you have to use the VectorFieldColorRenderer to display it.

Here is a working python example showing how GVF can be applied and visualized on a 2D grayscale image:
```python
import fast

importer = fast.ImageFileImporter.create(fast.Config.getTestDataPath() + "retina.png")
gradient = fast.ImageGradient.create().connect(importer)
gvf = fast.EulerGradientVectorFlow.create().connect(gradient)

renderer = fast.ImageRenderer.create().connect(importer)
renderer2 = fast.VectorFieldColorRenderer.create().connect(gvf)
fast.SimpleWindow2D.create().connect([renderer, renderer2]).run()
```

![Screenshot from 2021-09-13 10-57-33](https://user-images.githubusercontent.com/176325/133055781-6be1ccc4-253d-416e-ba39-22feab0dbc07.png)


For questions, please use the gitter chat instead: https://gitter.im/smistad/FAST

**Comment by libaineu2004** [comment]
OK. I hope to add GVF usage examples to https://github.com/smistad/FAST/tree/master/source/FAST/Examples

**Comment by libaineu2004** [comment]
How do I get the point coordinates of the contour processed by GVF?
