### ISSUE TITLE
levelset segmentation example don't get right result

### ISSUE THREAD

**Issue by feifeizuo** [smistad/FAST#151]
when I test levelset method through LevelSetTests.cpp , I got an error segmentation result.

**System:**
- OS and version: Windows 10 x64.
- GPU and OpenCL vendor (NVIDIA 3090)

Screen shot as below:

![image](https://user-images.githubusercontent.com/6001243/145153142-9d92bbf7-1559-458c-83f3-30ed4d0f49fa.png)

**Comment by smistad** [comment]
It seems I never finished this implementation for NVIDIA devices which does not support writing directly to 3d images/textures on the GPU
