### ISSUE TITLE
PW classifier predictions are off-by-one when renderering

### ISSUE THREAD

**Issue by andreped** [smistad/FAST#152]
**Describe the bug**
When running a simple pw-classification pipeline, using runPipeline, I observed that the predictions were off-by-one. Both horizontally and vertically.

**To Reproduce**
The FPL file and corresponding model and WSI can be downloaded from this URL:
https://drive.google.com/drive/folders/1jeovs5hco5U2wPrTHXiWghwiaugP6F6L?usp=sharing

Simply update the paths and run using runPipeline.

To make it easier to debug, I would disable heatmap interpolation (that is `useInterpolation = false` in FP). I have not started doing heatmap stuff with runPipeline yet in FP by default, and therefore not noticed that this was not possible to set this using an Attribute with Pipelines. Simply add option for Attribute here (setInterpolation method already exists):
https://github.com/smistad/FAST/blob/e47eb8bb75dbb5f4a9983471d261edd09b5250cf/source/FAST/Visualization/HeatmapRenderer/HeatmapRenderer.cpp#L16

Otherwise I can make a PR for that.

**System:**
- Bug found using Windows 10
- Both NVIDIA and Intel OpenCL vendors were tested and produced the same bug

**Expected behavior**
One-to-one correspondence between WSI and heatmap, aligned in a way that makes sense.

**Screenshots**
![example-off-by-one](https://user-images.githubusercontent.com/29090665/152348239-60d938a8-93bc-4da2-a13d-c04390f3909c.png)

**Disclaimer**
The newest commit of FAST was not used for doing the tests, but rather an older release (probably a month old). If it works for you I can try updating FAST and redoing the tests.

**Comment by smistad** [comment]
Patch generator was skipping patches at top and left edges, this was fixed in: https://github.com/smistad/FAST/commit/e8ad46f108053307d11f66508c6fe4110fa79b3e

Still, there is functionality missing for stitching tensor patches (https://github.com/smistad/FAST/blob/master/source/FAST/Algorithms/ImagePatch/PatchStitcher.cpp#L89) including:

- [ ] Handling out-of-bounds
- [ ] Handling overlap
- [ ] Stitching should happen on GPU, not via CPU

**Comment by smistad** [comment]
I think this might be fixed now, works fine here at least.
