### ISSUE TITLE
SurfaceExtration crash for big volume( = 4GB )

### ISSUE THREAD

**Issue by feifeizuo** [smistad/FAST#156]
Hi,
I use surfaceextration for a large CT volume with size (dimx = 1903, dimy = 1024, dimz = 1069), type is ushort. but it's crash with 
<img width="481" alt="image" src="https://user-images.githubusercontent.com/6001243/162704712-31c13ae8-9e99-4503-ac5e-11ff465e0991.png">
My PC have enough RAM and GPU Memory, why this happen ?

Thanks.

**System:**
- OS and version: [Windows 11 x64]
- GPU and OpenCL vendor (NVIDIA GTX 3090 24 GB, OpenCL 1.2)
- RAM: [128 GB]

**Expected behavior**
SurfaceExtration work well for large ct.

**Comment by smistad** [comment]
There are limits to how large buffers can be in OpenCL. Try resizing your volume to 1024x1024x1024 before the surface extraction and see if that works.  

C++ example: 
```c++
auto resizer = ImageResizer::create(1024, 1024, 1024)
    ->connect(image);
auto extraction = SurfaceExtraction::create()
    ->connect(resizer);
```
