### ISSUE TITLE
ImageFileStreamer always converts RGB input to grayscale

### ISSUE THREAD

**Issue by andreped** [smistad/FAST#170]
**Describe the bug**
In a bronchoscopy project, it was of interest to use FAST to enable real time deployment of temporal neural networks. However, we ran into issues at the very first step, where the [ImageFileStreamer](https://github.com/smistad/FAST/blob/master/source/FAST/Streamers/ImageFileStreamer.cpp) converted the RGB images to grayscale.

From what I can see, the ImageFileStreamer uses ImageFileImporter (see [here](https://github.com/smistad/FAST/blob/master/source/FAST/Streamers/ImageFileStreamer.cpp#L21)), which in turn uses [ImageImporter](https://github.com/smistad/FAST/blob/master/source/FAST/Importers/ImageFileImporter.cpp#L86). The ImageImporter includes a method (and option) for setting whether to convert to grayscale or not (see [here](https://github.com/smistad/FAST/blob/master/source/FAST/Importers/ImageImporter.cpp#L89)), though for the ImageFileImporter this is not exposed.

I believe adding an API option to set this for the ImageFileStreamer and ImageFileImporter would be of interest.

Just remember to make this possible to set in FPLs as well.

**To Reproduce**
The pipeline we are working on is somewhat similar to [this](https://fast.eriksmistad.no/export_visualization_to_video_8py-example.html) example.

**System:**
- OS and version: [e.g. Windows 10/Ubuntu 18.04] macOS 13.0 (M1 chip)
- GPU and OpenCL vendor (NVIDIA, AMD, Intel): Apple?

**Expected behavior**
The ImageFileStreamer should produce RGB output if requested.

cc: @AI-Ingrid

**Comment by smistad** [comment]
A fix for this has been pushed. Note the ImageImporter will default to no grayscale conversion now.
