### ISSUE TITLE
complile failure

### ISSUE THREAD

**Issue by zhanglin-1993** [smistad/FAST#186]
**Describe the bug**
I have downloaded the source code, build and compile the project FAST on my drive. The  compile error told me the openslide-win64-20171122.zip and cast-10.3.0-windows.zip has fail downloaded

**To Reproduce**
Steps and data to reproduce the behavior
I have downloaded the source code, build and compile the project FAST on my drive. The  compile error told me the openslide-win64-20171122.zip and cast-10.3.0-windows.zip has fail downloaded, then I follow your suggestions, download these two zip and unzip on the folder parrallel to that of FAST-master. After compile again, the result shows no error related to the cast, but the error of openslide still exsits. On the other hand, while the two zip has been unzipped to the drive, the compile release note has suggest that the zip is still been download.

**System:**
- windows 11
- OpenCL 3.0 - NVIDIA GeForce RTX 3060 Laptop GPU
- OpenGL 4.6 (432 ext) - NVIDIA GeForce RTX 3060 Laptop GPU

**Expected behavior**
I have expected the compile would search and find the unzipped cast and openslide files, and use them to compile the FAST, while the notes show that the two zips have been download again, and the compile is failed.

**Screenshots**
![image](https://github.com/smistad/FAST/assets/17542372/55095764-424e-43f1-a9bf-2dd44e2bfeca)
![image](https://github.com/smistad/FAST/assets/17542372/39cd5903-4644-47b0-89ac-d5cac7627d70)

Could you help me? Thanks so much!

**Comment by smistad** [comment]
Hi @zhanglin-1993, sorry for the late reply.
I am not sure what is causing this.
I would try to delete the external/clarius and external/openslide folders and then try and build again. This should download the zip files automatically and compile everything as usual.

**Comment by zhanglin-1993** [comment]
That's all right, thanks for sharing your experience. 
I have installed again and it seems work.
Thanks!
