### ISSUE TITLE
Error in network.runAndGetOutputData()

### ISSUE THREAD

**Issue by ggg5438** [smistad/FAST#202]
Thank you for your great work.

I followed [your tutorial](https://fast.eriksmistad.no/python-tutorial-neural-networks.html), but there is an error where Kernel died.

![image](https://github.com/smistad/FAST/assets/6397740/7a866a39-adf1-4475-8d63-09480567ffd1)

I am using Ubuntu 20.04, and python 3.8.
Is there any other requirements for the code, including the version of tensorflow?

**Comment by smistad** [comment]
Hi @ggg5438 

Thank you for reporting this.
It seems there is a missing a \ and the end of the line .create(fast.Config.getTestDataPath() + 'NeuralNetworkModels/jugular_vein_segmentation.onnx')

So the example should be like this:
```python
import fast

# Set up image importer to load an ultrasound image
importer = fast.ImageFileImporter\
    .create(fast.Config.getTestDataPath() + '/US/JugularVein/US-2D_100.mhd')

# Load neural network from a file and connect it to the importer
network = fast.NeuralNetwork\
    .create(fast.Config.getTestDataPath() + 'NeuralNetworkModels/jugular_vein_segmentation.onnx')\
    .connect(importer)

# Run the pipeline and get the resulting tensor
tensor = network.runAndGetOutputData()
print('Shape of output tensor is ', tensor.getShape().toString())
```
