### ISSUE TITLE
Nifti file now show

### ISSUE THREAD

**Issue by x1y9** [smistad/FAST#205]
**Describe the bug**
Using NIFTIImporter to show .nii.gz file, The image show not correctly.

**To Reproduce**
```
importer = fast.NIFTIImporter.create(r"D:\temp\ctchest.nii.gz")
fast.SlicerWindow.create().connectImage(importer).run()
```

**System:**
- OS and version: Windows10

**Screenshots**
![image](https://github.com/smistad/FAST/assets/26735696/a80d53d0-904e-4a22-8728-3adc60abfe65)

**Comment by smistad** [comment]
Thanks for reporting this @x1y9 
Are you able to share the ctchest.nii.gz file so I can try to reproduce the error?

**Comment by x1y9** [comment]
@smistad you can download the file here: https://drive.google.com/file/d/1mVQe0a2jH3hDDIopQzv3mrpLqpIRBTmE/view?usp=sharing

**Comment by smistad** [comment]
The bug should be fixed now.
You can download and install the new python wheel for windows here when it is done building (bottom of the page under "artifacts"): https://github.com/smistad/FAST/actions/runs/7887990650

![image](https://github.com/smistad/FAST/assets/176325/3d5a382e-6522-4ffc-8bb1-d6f07d1d1212)
