### ISSUE TITLE
Not able to access data from FAST DataHub

### ISSUE THREAD

**Issue by richamuktibodh** [smistad/FAST#208]
When executing the following python code on my idle:
model = fast.DataHub().download('nuclei-segmentation-model')
I get the following error:
RuntimeError: Failed to retrieve data from FAST DataHub. Server could be down, or you may have no internet access. Please try again later.

Python version - 3.11.5
OS - Windows 11

**Comment by andreped** [comment]
@richamuktibodh I think the Data Hub is down or something like that. At least I am unable to access the website anymore (see image below).

Sadly, @smistad will be away for a while, so I am not sure when this will be fixed.

<img width="1790" alt="Screenshot 2024-06-04 at 18 54 43" src="https://github.com/smistad/FAST/assets/29090665/8706b4eb-6cf0-47d3-910a-a1d02fcceb1c">

**Comment by smistad** [comment]
Had some server issues this summer. This should be fixed now.
