### ISSUE TITLE
read ome.tiff (uint8, 3 channels)

### ISSUE THREAD

**Issue by mhoibo** [smistad/FAST#210]
Hi, 

I am not completely sure this is a fast issue (or an issue with my images), but I have had issues reading ome.tiff (uint8 with 3 channels) images with fast (TIFFImagePyramidImporter.).  I can open the images with for example qupath, and they look good.  uint16 one channel ome.tif images works. 

When trying to extract a specific level from an image where 10 levels are found like this: 

```
fast.Reporter.setGlobalReportMethod(fast.Reporter.COUT)
path = '/path/to/image/'
importer = fast.WholeSlideImageImporter.create(path)
image = importer.runAndGetOutputData().getAccess(fast.ACCESS_READ).getLevelAsImage(level=level)
```
I get this error for level 4-7:

`Segmentation fault (core dumped)` when running from the terminal. When running from pycharm I just get an error code. 

For level 8+ it works. (and per usual levels below four are too large).

I can see that the levels exist, but it only seems to work for levels where the tile size is sufficiently small. 

I have had similar problems with getPatchAsImage and the patchGenerator.

Thank you in advance!

**Comment by smistad** [comment]
What are the sizes and tile sizes of each level?
Also could you share the failing image with me?

**Comment by smistad** [comment]
Hi @mhoibo 
The bug was fixed, and new wheels are being built on github: https://github.com/smistad/FAST/actions/runs/10489573260
I discovered another bug as well though, which makes the image for level 7 in look incorrect.

**Comment by mhoibo** [comment]
Thank you so much, @smistad!
