### ISSUE TITLE
Unable to download test data

### ISSUE THREAD

**Issue by general-rishkin** [smistad/FAST#218]
**Describe the bug**
I am unable to download the test data either from using pyFAST or via ./downloadTestData .

In both cases, I get the following error:

> WARNING [126076006436480] Test data was NOT found at /home/gennadiy/FAST/data/. Download the test data by running ./downloadTestData or fast.downloadTestDataIfNotExists() in Python.
> Downloading test data (~2GB) to /home/gennadiy/FAST/data/
> Progress: 
> 100% - ETA ~0 minutes. 
> 100% - ETA ~0 minutes. 
> Finished downloading file. Processing..
> Unzipping the data file ...
> ERROR: Zip extraction failed.
> Done.

The ~/FAST/Data and /FAST/pipelines directories are created but the Data directory is empty.

**System:**
- OS and version: Ubuntu 24.04

**Comment by general-rishkin** [comment]
With `fast.Reporter.setGlobalReportMethod(fast.Reporter.COUT)`, the only extra addition is this:

`INFO [137085812174336] QApp already exists..`

**Comment by general-rishkin** [comment]
I have just tried this on Windows and I get exactly the same result:
![image](https://github.com/user-attachments/assets/cb0b80da-1ffe-42ff-a59e-2b6d30d654c6)

**Comment by andreped** [comment]
> Probably a server issue. I will take a look later today

Would be nice to have a more informative exception handling if that was the case.

Now it sounds like zip extraction is the issue, which I doubt is the case?

When looking at the code, I see that a very broad exception is used (see [here](https://github.com/smistad/FAST/blob/6b1687072e7e2b23ae61ae445684e38d9182a323/source/FAST/Config.cpp#L397)), so it is hard to know exactly what is the issue. I would think the file just doesn't exist, hence why it is unable to do zip extraction.

**Comment by general-rishkin** [comment]
In addition, when I try to download a specific file, i.e.,

model = fast.DataHub().download('jugular-carotid-ultrasound-segmentation')

I get this error:

![image](https://github.com/user-attachments/assets/4d5f566f-c3a3-4dab-96c7-083b1c8006cf)

> File "C:\Users\gennadiy\AppData\Local\Programs\Python\Python310\lib\site-packages\fast\fast.py", line 18989, in download
>     return _fast.DataHub_download(self, itemID, force)

![image](https://github.com/user-attachments/assets/2c497732-a14d-4dff-845b-320d54f466b5)

I am using the latest version, 4.9.2.

**Comment by andreped** [comment]
> I am using the latest version, 4.9.2.

I guess you will have to use an older version of `pyfast` to use this exact model, as described in the last line there. For instance:
```
pip install pyfast==4.7.0
```

I guess @smistad can say more specifically why that model requires that. Could be that this model requires an older version of some inference engine, for instance. Not sure.

**Comment by smistad** [comment]
Hi @general-rishkin 

I found the error; the server I have hosted the test data suddenly does a redirect, and FAST is not setup to follow redirects.
I am creating a patch now.
In the meantime you can download the test data manually from here: https://smistad.folk.ntnu.no/fast/FAST_Test_Data.zip
and unzip it to /home/<username>/FAST/data/ or C:/Users/<username>/FAST/data/ on windows

**Comment by general-rishkin** [comment]
Thanks, all works well now.
