### ISSUE TITLE
undefined reference to symbol 'XOpenDisplay'?

### ISSUE THREAD

**Issue by petteriTeikari** [smistad/FAST#56]
I ran into the following error with <code>make</code> in Ubuntu 14.04 64-bit, and the AMD-APP-SDK-v3.0-0.113.50-Beta

<code>
Linking CXX executable test
/usr/bin/ld: libOpenCLUtilityLibrary.a(Context.cpp.o): undefined reference to symbol 'XOpenDisplay'
//usr/lib/x86_64-linux-gnu/libX11.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [test] Error 1
make[1]: *** [CMakeFiles/test.dir/all] Error 2
make: *** [all] Error 2
</code>

I was missing the <code>xorg-dev</code> pointed out <a href="http://ubuntuforums.org/showthread.php?t=1402709">there</a> but installing that did not really fix anything. Any idea how this could be corrected? Is my X11 configuration just off or is <a href="https://github.com/tum-vision/lsd_slam/issues/29">something missing</a> from the CMakeLists.txt. Or is the problem in the ATI drivers or the OpenCL?

Best,
Petteri

**Comment by smistad** [comment]
This is most likely that X11 is not being linked properly on your system. This is strange as I use the same system as you. Try to change the following line in your OpenCLUtilityLibrary/CMakeLists.txt file:

```
target_link_libraries(OpenCLUtilityLibrary ${OpenCLUtilityLibrary_LINK_LIBRARIES})
# Change to:
target_link_libraries(OpenCLUtilityLibrary ${OpenCLUtilityLibrary_LINK_LIBRARIES} X11)
```

**Comment by petteriTeikari** [comment]
That indeed helped @smistad and I got the make through :+1:

**Comment by smistad** [comment]
Excellent, I will make a patch for it tomorrow. Thanks for reporting it.
