### ISSUE TITLE
The simpleGUI example seg faults

### ISSUE THREAD

**Issue by smistad** [smistad/FAST#68]
When changing parameters in the GUI.
Happens during glDrawArrays in TriangleRenderer.
Affected systems: Windows 10 and Ubuntu 16 + AMD GPU

**Comment by DeveloperPaul123** [comment]
@smistad My Nvidia driver crashes when I change the HU threshold too fast: 

![image](https://cloud.githubusercontent.com/assets/6591180/26785883/8431168e-49d2-11e7-8176-de11cfc99ea3.png)

This is with a Quadro K2200.

**Comment by smistad** [comment]
I think this was fixed yesterday, with commit 409671f. Did you use this patch?

**Comment by DeveloperPaul123** [comment]
@smistad Yes I'm on the 7ae4987 commit from June 5th.

**Comment by smistad** [comment]
Hm, works fine here. See in commit 409671f, try to uncomment the line in the freeAll method in the mesh object starting with VertexBufferObjectAcceess. Does that fix the problem?

**Comment by DeveloperPaul123** [comment]
@smistad That helps with the issue above, but when I go below a certain HU threshold (about -21) I get an access violation. 

Also the driver just complete freezes whenever I try to change the smoothing at all. 

Additionally, when I monitor GPU usage I see that my Quadro is at 90% utilization when running the simpleGUI example. Could this be just the card running out of memory?

**Comment by smistad** [comment]
This example can use up your memory. But smoothing should work. I will have at look at it on my Nvidia+windows machine tomorrow

**Comment by DeveloperPaul123** [comment]
Sounds good.
