### ISSUE TITLE
Use Prebuilt Qt5

### ISSUE THREAD

**Issue by DeveloperPaul123** [smistad/FAST#78]
It would be nice to be able to use pre-built binaries of Qt5 instead of having cmake auto download and build Qt 5.8. This would save both time and space on the host machine. 

Basically this could be an `option` in cmake that would either use `find_package` or use the `ExternalQt5.cmake` script to auto download and build Qt5.

**Comment by smistad** [comment]
Yes, I have been planning to do that. Note however that fast works best with 5.8 there are some runtime issues with previous versions

**Comment by DeveloperPaul123** [comment]
@smistad Yes I've run into them myself. I tested on one machine that has Qt 5.7 and I ran into issues with `qtimer`. I'll retry with Qt 5.8 and if it works I can make a PR with the changes.

**Comment by DeveloperPaul123** [comment]
Closing this since #80 was merged.
