### ISSUE TITLE
Default Directories

### ISSUE THREAD

**Issue by DeveloperPaul123** [smistad/FAST#79]
In CMake, if you don't set the `FAST_TEST_DATA_DIR`, by default the data is downloaded to the source directory under `data/`. 

By default, the configuration file doesn't have a data directory set because the `FAST_TEST_DATA_DIR` variable is empty: 
````cmake
# from CMakeList.txt, line 170
# If test data dir has been set by user, write it to config file
if(NOT FAST_TEST_DATA_DIR STREQUAL "")
    # Remove any existing "
    string(REPLACE "\"" "" FAST_TEST_DATA_DIR ${FAST_TEST_DATA_DIR})
    message("-- FAST test data directory set to: \"${FAST_TEST_DATA_DIR}\"")
    set(CONFIG_TEST_DATA_PATH "TestDataPath = ${FAST_TEST_DATA_DIR}/")
endif()
````

When reading the configuration file during the tests, the data path defaults to a directory named `data` in the **build** directory. 

The same is true of the `KernelSourcePath` (see lines 71-80 of `Config.cpp`).

````c++
void loadConfiguration() {
    if (mConfigurationLoaded)
    	    return;

    // Set default paths
    mTestDataPath = getPath() + "../data/";
    mKernelSourcePath = getPath() + "../source/FAST/";
    mKernelBinaryPath = getPath() + "kernel_binaries/";
    mDocumentationPath = getPath() + "../doc/";
    mPipelinePath = getPath() + "../pipelines/";
    //....
}
````

The simple fix is to set the KernelSourcePath to a default value and to set the `FAST_TEST_DATA_DIR` variable to the default value if the user doesn't set it explicitly.

**Comment by smistad** [comment]
getPath() returns the path to the build directory, so getPath() + "../data/". Should become root/build/../data/, which gets resolved to root/data/. I have never had issues with this, so not sure how to reproduce what you are seeing?

**Comment by DeveloperPaul123** [comment]
@smistad My is build is not in the same directory as my source. I typically do out of source builds which keeps things much cleaner on my machine. So my source is in `C:/Repositories/FAST` and my build it in `C:/Repositories/Fast-build`. This way build and source are completely separate. 

So on my machine, getPath() + "../data/" gets resolved to .../Fast-build/data not .../Fast/data. 

In general (at least on windows) it's best to do out of source builds with cmake since that's kind of the point of the tool (to seperate source and build).

Is this structure different than what you're using? I should also note I'm using windows, so this could be a windows specific thing?

**Comment by smistad** [comment]
I see, personally I prefer to have the build dir in the root directory. But I know many prefer your method, and fast should definitely support it

**Comment by DeveloperPaul123** [comment]
@smistad Yeah it's probably more common on windows than anything else. This is mostly because we at times have to support multiple compilers so we do multiple builds of the same source.

**Comment by DeveloperPaul123** [comment]
Closing this since #80 was merged.
