### ISSUE TITLE
AirwaySegmentation Test Crashes with Access Violation

### ISSUE THREAD

**Issue by DeveloperPaul123** [smistad/FAST#81]
Every time I run the airway segmentation test the test fails because of an access violation. Below is the last part of the output before it crashes. Looks like it gets up to the point where it's checking the local convention for the decimal point and then the surface extraction?

My computer has 2 NVIDIA cards: a Tesla C2075 and a Quaddrro K2200. 

![image](https://cloud.githubusercontent.com/assets/6591180/26686134/12e5aa96-46ba-11e7-85c8-5b0dccd57c83.png)

**Comment by smistad** [comment]
It seems to be finished with the actual airway segmentation and centerline extraction. It's the visualization and thereby the extraction of the surface mesh from the segmentation (marching cubes algorithm) which seems to fail. This algorithm works on fine on my setup with Linux+NVIDIA/AMD and Windows+AMD. I will test it on Windows+NVIDIA and see if I can reproduce the error.

**Comment by DeveloperPaul123** [comment]
@smistad Here's some more output that might be helpful:

![image](https://cloud.githubusercontent.com/assets/6591180/26697275/5f2c5ee8-46df-11e7-9e49-3e74a993785b.png)

**Comment by DeveloperPaul123** [comment]
As an update, I was able to successfully build and run the tests on another machine with Visual Studio 2017, Qt 5.9, running windows 8.1 with an NVIDIA 860M. Looks like this bug may be system dependent. 

Do you think it could be driver related?

**Comment by smistad** [comment]
Could be. Would not be the first time. Which driver versions do you​ have?

**Comment by DeveloperPaul123** [comment]
I'm using driver version 376.51.

**Comment by DeveloperPaul123** [comment]
I upgraded to 377.35 and am still getting the same issue.

**Comment by DeveloperPaul123** [comment]
@smistad As an update, I removed the Tesla from my system, re-booted and tried the tests again and they all passed. So it seems that the Tesla was causing the issue. 

In my system configuration I had set the Tesla to be for `Compute Needs Only` so do you think the issue could have been that the code was trying to create a OpenGL context from the Tesla card (instead of my Quaddrro)?

**Comment by smistad** [comment]
I see. Only the Quadro is connected to a screen, right? But from the output above I see the Tesla is reported to have OpenGL interop, which is incorrect... I think. A card not connected to a screen should not have GL interop

**Comment by DeveloperPaul123** [comment]
@smistad Yes that's correct the Quadro (excuse my inability to spell) is connected to 2 monitors. The Tesla is not connected to any screens. I tried that once and it was terrible. 

I see. If that's the case then use, the Tesla should not have Open GL interop.
